name: Run Python Script

on:
  workflow_dispatch:   # <-- enables manual run

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script with token
        env:
          MY_API_TOKEN: ${{ secrets.MY_API_TOKEN }}
        run: python my_script.py
